/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package puntoventa;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author imano
 */
public class Sales extends javax.swing.JFrame {

    private boolean bloquearEventos = false;

    /**
     * Creates new form Sales
     */
    public Sales() {
        initComponents();
        lblDate.setText(GetDate());
        putItemsCBO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReturn = new javax.swing.JButton();
        cboProduct = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        spinQuantity = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        lblUnitPrice = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        btnInventary = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnReturn.setText("Return");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Return(evt);
            }
        });

        cboProduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboProduct.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                putPrice(evt);
            }
        });

        jLabel1.setText("Select the product:");

        jLabel2.setText("How much/many do u need?");

        spinQuantity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                TotalPrice(evt);
            }
        });

        jLabel3.setText("Unit Price:");

        lblUnitPrice.setText("$0.00");

        jLabel5.setText("Total: ");

        lblTotal.setText("$0.00");

        jButton1.setText("Buy");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buy(evt);
            }
        });

        jLabel4.setText("Date: ");

        lblDate.setText("00/00/0000");

        btnInventary.setText("Go to Inventary");
        btnInventary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goInventary(evt);
            }
        });

        btnReports.setText("Go to Reports");
        btnReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goReports(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(91, Short.MAX_VALUE)
                        .addComponent(btnReports)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInventary)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReturn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(spinQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblDate))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblUnitPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spinQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblTotal))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReturn)
                    .addComponent(btnInventary)
                    .addComponent(btnReports))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void putItemsCBO() {
        bloquearEventos = true;
        List<Map<String, Object>> datos = bd.leer(configuration, tabla);
        cboProduct.removeAllItems();
        cboProduct.addItem("SELECCIONE");
        for (Map<String, Object> fila : datos) {
            String nombre = fila.get("name").toString();
            cboProduct.addItem(nombre);
        }
        bloquearEventos = false;
    }

    private String GetDate() {
        SimpleDateFormat formateador = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Date date = new Date();
        String fechaFormateada = formateador.format(date);
        System.out.println(fechaFormateada);
        return fechaFormateada;
    }


    private void Return(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Return
        // TODO add your handling code here:
        new puntoventa().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Return

    private void goInventary(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goInventary
        // TODO add your handling code here:
        new Inventory().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_goInventary

    private void goReports(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goReports
        // TODO add your handling code here:
        new Reports().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_goReports

    private void Buy(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buy
        boolean canIbuy = false; //BANDERA
        int productID = 0;
        int stockQuantity = 0;
        double total = 0;

        // Leer productos de la BD
        List<Map<String, Object>> datos = bd.leer(configuration, tabla);

        // Datos seleccionados por el usuario
        int quantityToBuy = (Integer) spinQuantity.getValue();
        String productName = cboProduct.getSelectedItem().toString();

        // Validación de cantidad
        if (quantityToBuy <= 0) {
            JOptionPane.showMessageDialog(
                    null,
                    "Intentas comprar 0 productos o cantidades negativas",
                    "ERROR",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        // Buscar el producto en la tabla
        for (Map<String, Object> fila : datos) {
            String nameDB = fila.get("name").toString();

            if (nameDB.equals(productName)) {
                productID = Integer.parseInt(fila.get("id").toString());
                stockQuantity = Integer.parseInt(fila.get("quantity").toString());

                double price = Double.parseDouble(fila.get("sale_price").toString());
                total = quantityToBuy * price;

                // Validar existencia
                if (quantityToBuy > stockQuantity) {
                    JOptionPane.showMessageDialog(
                            null,
                            "Intentas comprar más productos de los disponibles",
                            "ERROR",
                            JOptionPane.ERROR_MESSAGE
                    );
                    return;
                }

                canIbuy = true;
                break;
            }
        }

        if (!canIbuy) {
            JOptionPane.showMessageDialog(null, "Producto no encontrado en BD.");
            return;
        }

        Map<String, Object> updateProduct = new HashMap<>();
        int newQuantity = stockQuantity - quantityToBuy;
        updateProduct.put("quantity", newQuantity);
        bd.actualizar(productID, updateProduct, configuration, "products");

        Map<String, Object> datosSales = new HashMap<>();
        datosSales.put("sale_date", GetDate());
        datosSales.put("product_id", productID);
        datosSales.put("quantity_sold", quantityToBuy);
        datosSales.put("total", total);
        bd.crear(datosSales, configuration, "sales");

        JOptionPane.showMessageDialog(null, "Compra registrada correctamente");


    }//GEN-LAST:event_Buy

    private void putPrice(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_putPrice
        // TODO add your handling code here:
        if (bloquearEventos) {
            return;
        }
        List<Map<String, Object>> datos = bd.leer(configuration, tabla);
        String product = cboProduct.getSelectedItem().toString();
        for (Map<String, Object> fila : datos) {
            String products = fila.get("name").toString();
            if (products.equals(product)) {
                String salePrice = fila.get("sale_price").toString();
                lblUnitPrice.setText(salePrice);
                break;
            }
        }
    }//GEN-LAST:event_putPrice

    private void TotalPrice(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TotalPrice
        // TODO add your handling code here:
        if (bloquearEventos) {
            return;
        }

        int cantidad = (Integer) spinQuantity.getValue();

        if (cantidad <= 0) {
            lblTotal.setText("0.0");
        } else {
            List<Map<String, Object>> datos = bd.leer(configuration, tabla);
            String product = cboProduct.getSelectedItem().toString();

            for (Map<String, Object> fila : datos) {
                String products = fila.get("name").toString();

                if (products.equals(product)) {

                    double salePrice = Double.parseDouble(fila.get("sale_price").toString());

                    double totalPrice = salePrice * cantidad;

                    lblTotal.setText(String.valueOf(totalPrice));

                    break;
                }
            }
        }
    }//GEN-LAST:event_TotalPrice

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInventary;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnReturn;
    private javax.swing.JComboBox<String> cboProduct;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblUnitPrice;
    private javax.swing.JSpinner spinQuantity;
    // End of variables declaration//GEN-END:variables

    String[] configuration = {"localhost", "root", "", "pos_system"};
    MySQLGenerico bd = new MySQLGenerico();
    String[] campos = {"sale_id", "product_id", "quantity_sold", "subtotal"};
    String tabla = "products";

}
